apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sonarr.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "sonarr.name" . }}
    helm.sh/chart: {{ include "sonarr.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: "{{ .Values.storage.config.storageClassName }}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.config.size }}
