apiVersion: monitoring.appscode.com/v1alpha1
kind: PodAlert
metadata:
  name: {{ include "nzbget.fullname" . }}-pod-status
  labels:
    app.kubernetes.io/name: {{ include "nzbget.name" . }}
    helm.sh/chart: {{ include "nzbget.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nzbget.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  check: pod-status
  checkInterval: 30s
  alertInterval: 2m
