apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hydra2.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hydra2.name" . }}
    helm.sh/chart: {{ include "hydra2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hydra2.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hydra2.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        date/deploy-date: {{ now | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: "{{ .Values.runtime.puid }}"
            - name: PGID
              value: "{{ .Values.runtime.pgid }}"
            - name: TZ
              value: "{{ .Values.runtime.tz }}"
          ports:
            - name: http
              containerPort: 5076
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "hydra2.fullname" . }}-config
        - name: downloads
          path: /data/downloads
          nfs:
            server: "{{ .Values.storage.downloads.server }}"
            path: "{{ .Values.storage.downloads.path }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
