apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smtp-server.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "smtp-server.name" . }}
    helm.sh/chart: {{ include "smtp-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  smtpRelayHost: {{ .Values.smtpRelayHost | b64enc }}
  smtpRelayMyHostname: {{ .Values.smtpRelayMyHostname | b64enc }}
  smtpRelayUsername: {{ .Values.smtpRelayUsername | b64enc }}
