apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smtp-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "smtp-server.name" . }}
    helm.sh/chart: {{ include "smtp-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "smtp-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "smtp-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SMTP_RELAY_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "smtp-server.fullname" . }}-config
                  key: smtpRelayHost
            - name: SMTP_RELAY_MYHOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "smtp-server.fullname" . }}-config
                  key: smtpRelayMyHostname
            - name: SMTP_RELAY_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "smtp-server.fullname" . }}-config
                  key: smtpRelayUsername
            - name: SMTP_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "smtp-server.fullname" . }}-secret
                  key: smtpRelayPassword
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
      volumes:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
